version: '3.8'

services:
  # تطبيق Next.js
  web:
    image: ghcr.io/${GITHUB_REPOSITORY:-username/lastumrahgo-frontend}:latest
    container_name: umrahgo-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - umrahgo-network
    volumes:
      - ./public:/app/public:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Nginx كخادم عكسي
  nginx:
    image: nginx:stable-alpine
    container_name: umrahgo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      web:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - umrahgo-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

networks:
  umrahgo-network:
    driver: bridge

volumes:
  ssl_certs:
    driver: local
  logs:
    driver: local
